-- Summary MK Performing Loan for ECL (in PostgreSQL)
select pt_date,
    tenor,
    ecl_bucket,
    max_bucket,
    max_dpd,
    max_stage,
    max_col,
    product_code,
    int_real_rate,
    count(loan_no) as count_loan,
    count(distinct client_no) as count_cif,
    sum(cur_balance) as outstanding_principal,
    sum(total_int_accrued) as int_accrued,
    sum(ecl_prin + ecl_fac) as ecl_principal,
    sum(ecl_int) as ecl_interest,
    sum(ecl_fac + ecl_int + ecl_prin) as ecl_final
from public.backup_mk_diskon_data_mkdbmonthly2_202309
group by pt_date,
    tenor,
    ecl_bucket,
    max_bucket,
    max_dpd,
    max_stage,
    max_col,
    product_code,
    int_real_rate;
-- Settlement Listing
select product_code,
    tenor,
    date_format(loan_disbursement_date, "YYYY-MM-DD") as loan_disbursement_date,
    settle_date,
    settle_type,
    count(loan_No) as count_loan,
    count(distinct client_no) as client_no,
    sum(cur_balance) as cur_Balance,
    sum(outstanding_contractual) as outstanding_contractual,
    sum(unamortized_cost_fee) as unamortized_cost_fee,
    sum(last_repay_int) last_repay_int,
    sum(last_repay_ppal) last_repay_ppal
from dm.rep_fin_reg_db_master_kredit_settled_ss_m
where pt_date = "${pt_date}"
group by product_code,
    tenor,
    date_format(loan_disbursement_date, "YYYY-MM-DD"),
    settle_date,
    settle_type;
-- Write off Listing
select pt_date,
    product_code,
    written_off_date,
    clawback_date,
    refund_date,
    day_past_due,
    day_past_due_write_off,
    tenor,
    count(loan_No) as count_loan,
    count(distinct client_no) as client_no,
    sum(write_off_principal) as write_off_principal,
    sum(write_off_interest) write_off_interest,
    sum(nvl(recovery_interest, 0)) as recovery_interest,
    sum(recovery_interest_ytd) as recovery_interest_ytd,
    sum(nvl(recovery_principal, 0)) as recovery_principal,
    sum(nvl(recovery_principal_ytd, 0)) as recovery_principal_ytd,
    sum(nvl(clawback_principal, 0)) as clawback_principal,
    sum(nvl(clawback_principal_ytd, 0)) as clawback_principal_ytd,
    sum(nvl(clawback_interest, 0)) as clawback_interest,
    sum(nvl(clawback_interest_ytd, 0)) as clawback_interest_ytd,
    sum(nvl(refund_principal, 0)) as refund_principal,
    sum(nvl(refund_principal_ytd, 0)) as refund_principal_ytd,
    sum(nvl(refund_interest, 0)) as refund_interest,
    sum(nvl(refund_interest_ytd, 0)) as refund_interest_ytd
from dm.rep_fin_reg_db_master_kredit_write_off_ss_d
where pt_date = "${pt_date}"
group by pt_date,
    product_code,
    written_off_date,
    clawback_date,
    refund_date,
    day_past_due,
    day_past_due_write_off,
    tenor;