__app_name__ = "Algobro Finance"
__version__ = "1.0.0"

"""LIST OF ACCOUNTING STATUS CODE: BALANCED, ERROR UNBALANCED"""
(
    BALANCED,
    UNBALANCED
) = range(2)

"""LIST OF BASE ACCOUNTING REPORT CODE: ASSET, PAYABLES, EQUITY, INCOME, EXPENSES"""
(
    ASSETS,
    PAYABLES,
    EQUITY,
    INCOME,
    EXPENSE
) = range(5)

"""LIST OF WORK TRANSACTION STATUS CODE"""
(
    SUCCESS,
    INCOMING,
    OUTGOING,
    PENDING,
    AUTHORIZING,
    WAITING_CONFIRMATION,
    CANCELLED,
    REFUNDED,
    OVERDUE
) = range(8)

"""LIST OF PAYMENT TRANSACTION STATUS CODE"""
(
    RECEIVED,
    INCOMING,
    OUTGOING,
    PENDING,
    AUTHORIZING,
    WAITING_CONFIRMATION,
    CANCELLED,
    REFUNDED,
    OVERDUE
) = range(8)

ACCOUNTING_STATUS = {
    BALANCED: "report balanced",
    UNBALANCED: "report unbalanced"
}

REPORTING_ACCOUNT = {
    ASSETS :"Assets",
    PAYABLES :"Payables",
    EQUITY :"Equity",
    INCOME :"Income",
    EXPENSE :"Expense"
}